import DefaultLayout from "../components/DefaultLayout";
import { UserTypeProvider } from "../contexts/UserTypeContext";
export const metadata = {
  title: "Alnasiri",
  description: "Generated by create next app",
};
export default function WithHeaderLayout({ children }) {
  return (
    <UserTypeProvider>
      <DefaultLayout>{children}</DefaultLayout>
    </UserTypeProvider>
  );
}
