import DefaultLayout from "../components/DefaultLayout";
export const metadata = {
  title: "Alnasiri",
  description: "Generated by create next app",
};
export default function WithHeaderLayout({ children }) {
  return <DefaultLayout>{children}</DefaultLayout>;
}
