import React from "react";
import LawyersRegister from "../../components/Register/LawyersRegister";
export const metadata = {
  title: "نصيري-تسجيل المحامي",
  description: "Generated by create next app",
};
function page() {
  return <LawyersRegister />;
}

export default page;
