import ClientRegister from "../components/Register/ClientRegister";
export const metadata = {
  title: "Register - Alnasiri",
  description: "Generated by create next app",
};
export default function Register() {
  return (
    <>
      <ClientRegister/>
    </>
  );
}
